---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- DateTime: 2023-11-15 14:55
---

function http_post_client(url, body, timeout)
    local httpc = zhttp.new()


    timeout = timeout or 30000
    httpc:set_timeout(timeout)


    local res, err_ = httpc:request_uri(url, {
        method = "POST",
        body = body,
        headers = {
            ["Content-Type"] = "application/x-www-form-urlencoded",
        }
    })


    return res, err_
end

http_post_client("http://localhost:8080/log/send","{\"key1\":\"value1\"}")