---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- DateTime: 2023-11-21 17:29
---
--- 示例
local method = ngx.var.request_method;
if method == 'PUT' then
    local dkjson = require("dkjson")
    local resty_http = require "resty.http"
    local httpc = resty_http.new()
    httpc:set_timeout(5000)
    local tokenUrl = 'xxxxxxxxxxxxxxxxxxxxxxx'
    local res, err = httpc:request_uri(tokenUrl, { method = "GET", headers = { ['Content-Type'] = 'application/json' }, query = { ['method'] = ngx.var.request_method }, keepalive_timeout = 30000, keepalive_pool = 16 })
    ngx.log(ngx.WARN, "http result:" .. res.body)
    if res and res.status == 200 and res.body ~= nil then
        local result = dkjson.decode(res.body, 1, nil)
        local signature = result.obj
        ngx.log(ngx.WARN, "signature:" .. signature)
        ngx.req.set_header('Authorization', "Bearer " .. signature)
    end
end


--- 增加请求头
local core = require("apisix.core") core.request.set_header(ctx,"X-Kong-NEW-Header","LLM_VALUE")
